### ISSUE TITLE
Improve error message when mapped user has no access to see the issue in Service Now

### ISSUE THREAD

**Issue by DHaussermann** [Brightscout/mattermost-plugin-servicenow#110]
When a user in Mattermost **is** connected to Service Now but does not have privileges to see the issue comments - The error is a ugly and cryptic. Maybe it could be translated to something more general?    
![image](https://user-images.githubusercontent.com/35588783/202002121-209d5f81-3391-49b0-a1ef-ddd770086106.png)

**Comment by manojmalik20** [comment]
This issue is already fixed in release 2.3.0. Please confirm and close this issue. @DHaussermann
