### ISSUE TITLE
Close `X` is not right aligned in modals 

### ISSUE THREAD

**Issue by DHaussermann** [Brightscout/mattermost-plugin-servicenow#111]
In the modals the close `X` is always at the end of the header text. It should be right aligned to look better and always be at the same place regardless of the text length.

![image](https://user-images.githubusercontent.com/35588783/202002634-9c5a702c-1dbd-4d47-8c30-8500283c4f12.png)

**Comment by ayusht2810** [comment]
This issue is fixed in the latest release v2.3.1. Please confirm and close this issue. @DHaussermann

**Comment by DHaussermann** [comment]
Thanks @ayusht2810 confirmed fixed on 2.3.1. 

Closing.
