### ISSUE TITLE
Add icon for Service Now header

### ISSUE THREAD

**Issue by DHaussermann** [Brightscout/mattermost-plugin-servicenow#112]
Can we add an icon for the header to Service Now. The slash commands and bot have an icon however the header dies not. 
![image](https://user-images.githubusercontent.com/35588783/202020781-fcbd7b4e-f5dd-4ea5-8cb6-08d19cbf1ba7.png)

**Comment by ayusht2810** [comment]
This icon is updated in the latest release v2.3.1. Please confirm and close this issue. @DHaussermann

**Comment by DHaussermann** [comment]
Thanks @ayusht2810 confirmed fixed on 2.3.1.
- Icon display as monochromatic in channel header  (as expected)
- Plugin shows coloured icon in Apps bar
- Icon has reasonable contrast in all themes 
- Icon has tool tip as expected

Closing.
