### ISSUE TITLE
"Invalid number of params for this command" is too technical

### ISSUE THREAD

**Issue by DHaussermann** [Brightscout/mattermost-plugin-servicenow#115]
Can we replace the text "Invalid number of params for this command" with something more clear and intuitive to all users?

![image](https://user-images.githubusercontent.com/35588783/202035423-55e13579-fdfd-43e8-bf25-232de2f2c777.png)

This could be replaced with something like "One or more fields is missing to run the command. Please run `/servicenow help` for more information"

**Comment by ayusht2810** [comment]
This issue is fixed in the latest release v2.3.1. Please confirm and close this issue. @DHaussermann

**Comment by DHaussermann** [comment]
Thanks @ayusht2810 confirmed fixed on 2.3.1.

Closing.
